class Login_Locators:
    User_Name_Field = "//input[@type='text']"
    Password_Field = "//input[@name='password']"
    Login_Button = "//ion-button[contains(.,'Login')]"


class Patients_Locators:
    Patient_Tab = "//ion-tab-button[contains(.,'Patients')]"
    Patient_Reg_Icon = "//ion-button[@shape='round']"
    New_Patient_Button = "//ion-text[@color='gray80'][contains(.,'New Patient')]"
    PGP_Dropdown_Arrow = "(//span[@class='k-button-icon k-icon k-i-caret-alt-down'])[9]"
    PGP_BOX = "(//input[@placeholder='*Physician Group'])[1]"
    FIRST_NAME_BOX = "//input[@placeholder='*First Name']"
    MIDDLE_NAME_BOX = "//input[@placeholder='Middle Name']"
    LAST_NAME_BOX = "//input[contains(@placeholder,'*Last Name')]"
    BIRTHDATE_FIELD = "//input[@id='datepicker-1']"
    GENDER_BOX = "//input[@placeholder='*Gender']"
    ADDRESS_FIELD = "//input[contains(@placeholder,'Address 1')]"
    ZIP_CODE_BOX = "//input[@placeholder='Zip']"
    MOBILE_NUMBER_FIELD = "(//input[contains(@type,'text')])[2]"
    HOME_NUMBER_FIELD = "(//input[contains(@type,'text')])[3]"
    EMAIL_BOX = "//input[contains(@placeholder,'Email')]"
    INSURANCE_ID_BOX = "//input[contains(@placeholder,'*ID')]"
    PHYSICIAN_DROPDOWN = "//input[@placeholder='*Physician']"
    INSURANCE1_DROPDOWN = "(//span[@ng-reflect-ng-class='k-i-caret-alt-down'])[13]"
    SAVE_INITIATE_EPISODE_BUTTON = "//ion-text[contains(.,'Save & initiate Episode')]"
    Save_Patient_button = "//ion-text[contains(.,'save & close')]"
    Plus_Button = "(//ion-button[@slot='only-icon'])[position()=12 or position()=14 or position()=16 or position()=17 or position()=13 or position()=22 or position()=21]"
    Office_No_Option = "//ion-text[contains(.,'Office')]"
    Fax_Number_Option = "//ion-text[contains(.,'Fax')]"
    Office_Number_Box = "/html/body/modal-container/div[2]/div/patient-registration/div/kendo-dialog/div[2]/div/div/episodic-patient-registration/div/div/ngx-simplebar/div[1]/div[2]/div/div/div/div/form/div/div[3]/div[2]/div[1]/div[3]/div[1]/div[1]/kendo-formfield/div/kendo-maskedtextbox/input"
    Fax_No_Box = "/html/body/modal-container/div[2]/div/patient-registration/div/kendo-dialog/div[2]/div/div/episodic-patient-registration/div/div/ngx-simplebar/div[1]/div[2]/div/div/div/div/form/div/div[3]/div[2]/div[1]/div[4]/div/div[1]/kendo-formfield/div/kendo-maskedtextbox/input"
    Group_ID_Box = "//input[@placeholder=' Group ID']"
    Note_Box = "//textarea[@placeholder='Notes']"
    Exclude_Report_Box = "//input[@type='checkbox']"
    Pin_Icon = "(//ion-button[@fill='clear'])[5]"


class Episodes_Locators:
    Patient_Tab = "//ion-tab-button[contains(.,'Patients')]"
    Description_Box = "//input[@placeholder='Description (e.g. Right Knee Surgery)']"
    Physician_Box = "//input[@placeholder='*Physician']"
    Program_Dropdown_Arrow = "(//span[@ng-reflect-ng-class='k-i-caret-alt-down'])[12]"
    Program_Box = "//input[@placeholder='*Program']"
    BCBS_Program = "//li[@index='0']"
    PGP_Box = "/html/body/modal-container/div[2]/div/episode-add-new-episode-popup/div/kendo-dialog/div[2]/div/div/ion-list/form/div/div[1]/div[1]/kendo-formfield[1]/div"
    Facility_Dropdown_Arrow = "(//span[@ng-reflect-ng-class='k-i-caret-alt-down'])[13]"
    Facility_Box = "//input[@placeholder='*Facility']"
    Surgical_Facility = "//span[contains(.,'ADVANCED NEUROLOGY CENTER, PLLC')]"
    Dropdown_index = "(//li[@role='option'])[position()=1 or position()=2 or position()=3 or position()=4]"
    Surgery_Date = "//input[@id='datepicker-2']"
    Type = "//input[@placeholder='*Type']"
    Hip_Box = "//ion-text[contains(.,'Hip')]"
    Knee_Box = "//ion-text[contains(.,'Knee')]"
    Ankle_Box = "//ion-text[contains(.,'Ankle')]"
    Shoulder_Box = "//ion-text[contains(.,'Shoulder')]"
    Save_Button = "//ion-button[contains(.,'Save')]"
    Risk_Button = "//div[@class='d-flex align-items-center'][contains(.,'Risk')]"
    Risk_Options = "//span[contains(., 'Low') or contains(., 'Medium') or contains(., 'High')]"
    Target_Price = "/html/body/app-root/ion-app/ion-router-outlet/app-main/div/app-patients/div/div/div/patient-content/episodes-list/ngx-simplebar/div[1]/div[2]/div/div/div/div/div/section/div[2]/ion-card/div[2]/div[1]/div[2]/div[2]/div"
    Target_Price_Box = "//input[@role='spinbutton']"
    Episode_Notes = "//ion-text[contains(.,'+ Note')]"
    Episode_Note_Box = "//input[@placeholder='Add a note']"
    Add_Note_Tick = "//ion-button[contains(@ng-reflect-disabled,'false')]"
    Care_Plan_Field = "/html/body/app-root/ion-app/ion-router-outlet/app-main/div/app-patients/div/div/div/patient-content/episodes-list/ngx-simplebar/div[1]/div[2]/div/div/div/div/div/section/div[2]/ion-card/div[2]/div[4]/div/div"
    Select_Index1_CarePlan = "//input[contains(@id,'tag0')]"
    Next_Button = "//ion-text[contains(.,'Next')]"
    Save_Button_2 = "//ion-text[contains(.,'Save')]"
    Initiate_Buttton = "//ion-text[contains(.,'Initiate')]"


class Activities_Locators:
    Activities_Tab = "/html/body/app-root/ion-app/ion-router-outlet/app-main/div/main-nav/ion-tab-bar/ion-tab-button[3]/ion-label"
    Activities_Plus_Button = "//div[contains(@class, 'row-verticalCenter')]//ion-text[contains(text(), 'Activities')]/following-sibling::div[contains(@class, 'dropdown')]/ion-button[contains(@class, 'round-icon-button')]"
    Call_Activity_Option = "//li[normalize-space()='Call']"
    Category_Dropdown = "//input[@placeholder='Category*']"
    Subject_Textbox = "//input[@placeholder='Subject*']"
    Assigned_To_Dropdown = "//input[@placeholder='Assigned To*']"
    Follow_up_Date_Dropdown = "//kendo-datepicker[@formcontrolname='exeStart']"
    Phone_Number = "//kendo-maskedtextbox[@formcontrolname='phone']"
    Save_Button = "//ion-text[contains(.,'Save')]"
    Form_Option = "//li[contains(.,'Form')]"
    Form_Box = "//input[@placeholder='Form*']"
    Form_Subject_Box = "//input[@placeholder='Subject*']"
    Save_Button_Form = "//ion-button[contains(.,'Save')]"





